Reactive
kermakovich/hospital-finance pull request #10
Opened 2023-03-08 17:17 UTC by kermakovich

2023-03-08 17:24 UTC, kermakovich commented
Open Feign was removed, because it doesn't support spring boot v. 3. Webflux is used instead

2023-03-09 10:56 UTC, h1alexbel requested changes

2023-03-09 10:56 UTC, h1alexbel commented on src/main/java/solvd/laba/ermakovich/hf/web/WebClientConfig.java
> +//                .defaultHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)
remove the comments

2023-03-09 11:00 UTC, h1alexbel commented
@kermakovich can you resolve merge conflict?

2023-03-09 11:11 UTC, kermakovich commented
@h1alexbel, conflict was resolved

2023-03-09 11:17 UTC, h1alexbel commented
@kermakovich thanks

2023-03-09 11:17 UTC, merged